SUBROUTINE CHGDIFF 
! THIS FILE IS PART OF THE VASPKIT PACKAGE.
! COPYRIGHT (C) 2014 V. WANG
! THIS FILE IS DISTRIBUTED UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE
  USE MODULE
  IMPLICIT NONE
  INTEGER :: I,J,K,N=2
  INTEGER :: GRIDSIZE(2,3)
  CHARACTER(LEN=50) :: CHGFILE_1,CHGFILE_2
  CHARACTER(LEN=30) :: OUTFILE 
  REAL(KIND=8), ALLOCATABLE :: RHOGRID_1(:,:,:)
  REAL(KIND=8), ALLOCATABLE :: RHOGRID_2(:,:,:)
  IF (LEN_TRIM(PARAMS(1)) .EQ. 0) THEN
     write(*,*)'================= File Options ======================'
     WRITE(*,*) 'Input the file names of two charge/potential files: '
     WRITE(*,*)
     write(*,*) '------------>>'
     READ(*,*) CHGFILE_1,CHGFILE_2
  ELSE
     CHGFILE_1='CHG1'
     CHGFILE_2='CHG2'
  ENDIF

  IF (TAG.EQ.34) THEN
     OUTFILE='CHGDIFF'//VASPSUFF
  ELSE IF (TAG.EQ.35) THEN
     OUTFILE='SPINDIFF'//VASPSUFF
  END IF

  OPEN(13,FILE=TRIM(OUTFILE))
! READ CHGFILE_1
  INFILE=TRIM(CHGFILE_1)
  CALL READRHO
  ALLOCATE(RHOGRID_1(NGX,NGY,NGZ))   
  GRIDSIZE(1,1)=NGX
  GRIDSIZE(1,2)=NGY
  GRIDSIZE(1,3)=NGZ
  CALL WRITEPOS

  IF (TAG.EQ.34) THEN
     RHOGRID_1=CHGRHO
  ELSEIF (TAG.EQ.35) THEN
     RHOGRID_1=SPINRHO
  END IF 
  CALL FREEMEMORY

! READ CHGFILE_2
  INFILE=TRIM(CHGFILE_2)
  CALL READRHO
  ALLOCATE(RHOGRID_2(NGX,NGY,NGZ))   
  GRIDSIZE(2,1)=NGX
  GRIDSIZE(2,2)=NGY
  GRIDSIZE(2,3)=NGZ
  IF (TAG.EQ.34) THEN
     RHOGRID_2=CHGRHO
  ELSEIF (TAG.EQ.35) THEN
     RHOGRID_2=SPINRHO
  END IF
  IF (GRIDSIZE(1,1) .NE. GRIDSIZE(2,1) .OR. GRIDSIZE(1,2) .NE. GRIDSIZE(2,2) &
     .OR. GRIDSIZE(1,3) .NE. GRIDSIZE(2,3)) THEN
     WRITE(*,*) 'ERROR: INCOMPATIBLE NGX, NGY OR NGZ IN TWO CHARGE FILES ARE DIFFERENT!'
     WRITE(*,*) 'NGX, NGY, NGZ OF CHGFILE_1: ',(GRIDSIZE(1,I),I=1,3)
     WRITE(*,*) 'NGX, NGY, NGZ OF CHGFILE_2: ',(GRIDSIZE(2,I),I=1,3)
  ELSE
     WRITE(13,*)
     WRITE(13,'(3I5)') NGX,NGY,NGZ
     WRITE(13,'(5E17.8E2)') (((RHOGRID_1(I,J,K)-RHOGRID_2(I,J,K),I=1,NGX),J=1,NGY),K=1,NGZ)
  END IF
  DEALLOCATE(RHOGRID_1)
  DEALLOCATE(RHOGRID_2)
  PROGRESS='Written '//TRIM(OUTFILE)//' File!'
  CALL READPRT
CLOSE(13)
RETURN
END SUBROUTINE
