SUBROUTINE OPTICS
! COPYRIGHT (C) 2009 V. WANG
! THIS FILE IS DISTRIBUTED UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE.
! SEE THE FILE COPYING FOR LICENSE DETAILS.
    USE MODULE 
    IMPLICIT NONE
    CHARACTER(LEN=12) :: IMAG_PART='IMAG.in', REAL_PART='REAL.in' 
    REAL(KIND=8):: ABSORB(6),REFRACTIVE(6),ENERGYLOSSSPECTRUM(6),EXTINCTION(6),REFLECTIVITY(6),FREQ 
    REAL(KIND=8) :: EN,EPSILON_REAL(6),EPSILON_IMAG(6)
    INTEGER :: I,J,OPENSTAT,IOSTAT=0
    WRITE(*,*)"+---------------------------------------------------+"
    WRITE(*,*)"|    Please prepared IMAG.IN and REAL.IN files      |"
    WRITE(*,*)"|               before runing optics                |"
    WRITE(*,*)"|...................................................|"
    WRITE(*,*)"|   Caculate absorb,refractive,energylossspectrum,  |"
    WRITE(*,*)"|        extinctionr and reflectivity (in eV).      |"
    WRITE(*,*)"+---------------------------------------------------+"
    WRITE(*,*)
    ! OPEN FILES
    OPEN(50,FILE=TRIM(IMAG_PART),FORM='FORMATTED',STATUS='OLD',ACTION='READ',IOSTAT=OPENSTAT)
    OPEN(60,FILE=TRIM(REAL_PART),FORM='FORMATTED',STATUS='OLD',ACTION='READ',IOSTAT=OPENSTAT)
    IF (OPENSTAT>0) THEN
       WRITE(*,*)"THE IMAG.in OR/AND REAL.in FILE(S) NOT EXIST!"
       GOTO 200
    END IF
    PROGRESS='READING IMAG.in and REAL.in FILES...'
    CALL READPRT
    OPEN(61,FILE='ABSORB'//DATSUFF,FORM='FORMATTED',STATUS='REPLACE',ACTION='WRITE')
    OPEN(62,FILE='REFRACTIVE'//DATSUFF,FORM='FORMATTED',STATUS='REPLACE',ACTION='WRITE')
    OPEN(63,FILE='ENERGYLOSSSPECTRUM'//DATSUFF,FORM='FORMATTED',STATUS='REPLACE',ACTION='WRITE')
    OPEN(64,FILE='EXTINCTION'//DATSUFF,FORM='FORMATTED',STATUS='REPLACE',ACTION='WRITE')
    OPEN(65,FILE='REFLECTIVITY'//DATSUFF,FORM='FORMATTED',STATUS='REPLACE',ACTION='WRITE')
    
     DO WHILE(IOSTAT==0)
        READ(60,*,IOSTAT=IOSTAT) EN, (EPSILON_REAL(J),J=1,6)
        READ(50,*,IOSTAT=IOSTAT) EN, (EPSILON_IMAG(J),J=1,6)
        FREQ=EN/H
        DO J=1,6
          ! UNIT (CM^-1)
          ABSORB(J)=1.4142*FREQ*(SQRT(-EPSILON_REAL(J)+SQRT(EPSILON_IMAG(J)*EPSILON_IMAG(J)&
                    +EPSILON_REAL(J)*EPSILON_REAL(J))))/(C0*100) 
          REFRACTIVE(J)=(SQRT(EPSILON_REAL(J)+SQRT(EPSILON_IMAG(J)*EPSILON_IMAG(J)+EPSILON_REAL(J)*EPSILON_REAL(J))))/1.4142
          ENERGYLOSSSPECTRUM(J)=EPSILON_IMAG(J)/(EPSILON_IMAG(J)*EPSILON_IMAG(J)+EPSILON_REAL(J)*EPSILON_REAL(J))
          EXTINCTION(J)=(SQRT(-EPSILON_REAL(J)+SQRT(EPSILON_IMAG(J)*EPSILON_IMAG(J)+EPSILON_REAL(J)*EPSILON_REAL(J))))/1.4142
          REFLECTIVITY(J)=((REFRACTIVE(J)-1)*(REFRACTIVE(J)-1)+EXTINCTION(J)*EXTINCTION(J))/&
                            ((REFRACTIVE(J)+1)*(REFRACTIVE(J)+1)+EXTINCTION(J)*EXTINCTION(J))
        END DO
      WRITE(61,'(F8.3,6E16.4)')EN,(ABSORB(J),J=1,6)
      WRITE(62,'(F8.3,6E16.4)')EN,(REFRACTIVE(J),J=1,6)
      WRITE(63,'(F8.3,6E16.4)')EN,(ENERGYLOSSSPECTRUM(J),J=1,6)
      WRITE(64,'(F8.3,6E16.4)')EN,(EXTINCTION(J),J=1,6)
      WRITE(65,'(F8.3,6E16.4)')EN,(REFLECTIVITY(J),J=1,6)
    END DO
    WRITE(*,*)
    PROGRESS='WRITTEN OPTICAL FILES SUCCESFULLY!'
    CALL READPRT
    CLOSE(50) 
    CLOSE(60)
    CLOSE(61)
    CLOSE(62)
    CLOSE(63)
    CLOSE(64)
    CLOSE(65)
    200  RETURN
END SUBROUTINE
