SUBROUTINE READPRT
! THIS FILE IS PART OF THE VASPKIT PACKAGE.
! COPYRIGHT (C) 2014 V. WANG
! THIS FILE IS DISTRIBUTED UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE
  USE MODULE
  IMPLICIT NONE 
  WRITE(*,200)' -->> (',COUNTER,') ',ADJUSTL(PROGRESS)
  COUNTER=COUNTER+1
  200 FORMAT(A7,I1,A2,A70)
END SUBROUTINE
