SUBROUTINE READFERMI
! THIS FILE IS PART OF THE VASPKIT PACKAGE.
! COPYRIGHT (C) 2014 V. WANG
! THIS FILE IS DISTRIBUTED UNDER THE TERMS OF THE GNU GENERAL PUBLIC
! LICENSE
USE MODULE
IMPLICIT NONE
! LOCAL VARIABLE
  REAL*8 :: AREA
  REAL*8 :: NORMALIZATION
  INTEGER :: I,J,K,ISERROR,TOTAL

! READ FERMI ENERGY AND ROWS
  OPEN(UNIT=15,FILE='DOSCAR',FORM='FORMATTED',STATUS='OLD',IOSTAT=ISERROR)
  IF (ISERROR>0) THEN
      WRITE(*,*)'Error Open: The DOSCAR File Does Not Exist'
      STOP
  END IF

  PROGRESS='Reading Fermi-Level From DOSCAR File...'
  CALL READPRT

! SKIP IFORMATION OF START
  DO I=1,5
     READ (15,*)
  END DO

! READ FERMI ENERGY AND ROWS
  READ (15,*)ENMAX,ENMIN,ROWS,EF
end subroutine 
