subroutine readkpt
! THIS FILE IS PART OF THE VASPKIT PACKAGE.
! COPYRIGHT (C) 2015 V. WANG
! THIS FILE IS DISTRIBUTED UNDER THE TERMS OF THE GNU GENERAL PUBLIC
! LICENSE
  USE MODULE
  IMPLICIT NONE
  PROGRESS='Reading Kmesh From KPOINTS File...'
  CALL READPRT
  OPEN(9,FILE='KPOINTS',FORM='FORMATTED',STATUS='OLD')
  READ(9,*) 
  READ(9,*) NDIV
  close(9)
  return
end subroutine 
