SUBROUTINE READPOS 
! THIS FILE IS PART OF THE VASPKIT PACKAGE.
! COPYRIGHT (C) 2014 V. WANG
! THIS FILE IS DISTRIBUTED UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE
  USE MODULE
  IMPLICIT NONE
  INTEGER :: I,J,ERROR,STATUS=0,L
  REAL(8) :: REALVECTOR_INV(3,3)    
  ATOMTYPE=1
  TOTALATOMS=0
  OPEN(UNIT=11,FILE=TRIM(ADJUSTL(INFILE)),FORM='FORMATTED',STATUS='OLD',IOSTAT=ERROR)
     IF (ERROR>0) THEN
      WRITE(*,*)' Input Error: The ', TRIM(ADJUSTL(INFILE)),' File Does Not Exist'
      WRITE(*,*)
  STOP
  END IF
  PROGRESS='Reading Atomic Positions From '//TRIM(ADJUSTL(INFILE))//' File...'
  CALL READPRT
  READ(11,'(A30)')TITLE
  READ(UNIT=11,fmt=*) SCALING
  READ(UNIT=11,FMT=*) ((REALVECTOR(I,J),J=1,3),I=1,3)
  DO I=1,3
     CALL GETMOD(REALVECTOR(I,:),LATTLEN(I))
  END DO
  LATTLEN=LATTLEN*SCALING

! CALCULATE THE ANGLE BETWEEN TWO THE LATTICE
  ALPHA=ACOS(DOT_PRODUCT(REALVECTOR(2,:),REALVECTOR(3,:))*SCALING**2/&
  (LATTLEN(2)*LATTLEN(3)))*180/PI
  BETA=ACOS(DOT_PRODUCT(REALVECTOR(1,:),REALVECTOR(3,:))*SCALING**2/&
  (LATTLEN(1)*LATTLEN(3)))*180/PI
  GAMMA=ACOS(DOT_PRODUCT(REALVECTOR(1,:),REALVECTOR(2,:))*SCALING**2/&
  (LATTLEN(1)*LATTLEN(2)))*180/PI
  CALL CROSS(REALVECTOR(:,2)*SCALING,REALVECTOR(:,3)*SCALING,RECIPVECTOR(:,1))
  CALL CROSS(REALVECTOR(:,3)*SCALING,REALVECTOR(:,1)*SCALING,RECIPVECTOR(:,2))
  CALL CROSS(REALVECTOR(:,1)*SCALING,REALVECTOR(:,2)*SCALING,RECIPVECTOR(:,3))
  VOLUME=REALVECTOR(1,1)*(REALVECTOR(2,2)*REALVECTOR(3,3)-REALVECTOR(2,3)*REALVECTOR(3,2))&
        +REALVECTOR(1,2)*(REALVECTOR(2,3)*REALVECTOR(3,1)-REALVECTOR(2,1)*REALVECTOR(3,3))&
        +REALVECTOR(1,3)*(REALVECTOR(2,1)*REALVECTOR(3,2)-REALVECTOR(2,2)*REALVECTOR(3,1))
  VOLUME=VOLUME*SCALING**3
  RECIPVECTOR(:,:)=(2*PI/VOLUME)*RECIPVECTOR(:,:)

  IF (VASP5 .EQV. .TRUE.) READ(11,*)
  DO WHILE(STATUS<=0) 
     ALLOCATE(NATOMS(ATOMTYPE))
     READ(UNIT=11,FMT=*,IOSTAT=STATUS)(NATOMS(I),I=1,ATOMTYPE)
     ATOMTYPE=ATOMTYPE+1
     DEALLOCATE(NATOMS)
     BACKSPACE(11)
  END DO

   ATOMTYPE=ATOMTYPE-2
   ALLOCATE(ATOMSYMBOL(ATOMTYPE))
   ALLOCATE(NATOMS(ATOMTYPE))
   BACKSPACE(11)
   IF (VASP5 .EQV. .TRUE.) THEN
      BACKSPACE(11)
      READ(UNIT=11,FMT=*,IOSTAT=STATUS)(ATOMSYMBOL(I),I=1,ATOMTYPE)
   END IF

   READ(UNIT=11,FMT=*,IOSTAT=STATUS)(NATOMS(I),I=1,ATOMTYPE)
   DO I=1,ATOMTYPE
      TOTALATOMS=NATOMS(I)+TOTALATOMS
   END DO
   ALLOCATE(ATOMPOS(TOTALATOMS,3))
   ALLOCATE(ATOMPOS_CART(TOTALATOMS,3))
   READ(11,*)COORDTYPE
   IF ((COORDTYPE=='S').OR.(COORDTYPE=='S')) THEN
      READ(11,*)COORDTYPE
      WRITE(*,*)'Selective Dynamics is Activated!'
      WRITE(*,*)
   END IF
   IF ((COORDTYPE=='D').OR.(COORDTYPE=='d')) THEN
      DO I=1,TOTALATOMS
!  READ DIRECT COORDINRATE
         READ(11,*)ATOMPOS(I,:)
         ATOMPOS_CART(I,:)=MATMUL(ATOMPOS(I,:),REALVECTOR)*SCALING
      END DO 
   ELSE IF ((COORDTYPE=='C').OR.(COORDTYPE=='c')&
           .OR.(COORDTYPE=='K').OR.(COORDTYPE=='k')) THEN
      REALVECTOR_INV=REALVECTOR
      CALL BRINV(REALVECTOR_INV,3)
      DO I=1,TOTALATOMS
!  READ CARTESIAN COORDINRATE
         READ(11,*)ATOMPOS_CART(I,:)
         ATOMPOS(I,:)=MATMUL(ATOMPOS_CART(I,:),REALVECTOR_INV)/SCALING
      END DO 
   END IF
   IF (TAG .LT.10 ) THEN 
      CLOSE(11)
   ENDIF
RETURN
END SUBROUTINE
