SUBROUTINE WRITERHO
! THIS FILE IS PART OF THE VASPKIT PACKAGE.
! COPYRIGHT (C) 2014 V. WANG
! THIS FILE IS DISTRIBUTED UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE

! READ RHO FROM NAME=CHG FILE OF VASP
  USE MODULE
  IMPLICIT NONE
  INTEGER :: I,J,K
  IF (TAG.EQ.31) THEN
     OPEN(UNIT=13,FILE='CHARGE'//VASPSUFF)
  ELSE IF (TAG.EQ.32) THEN
     OPEN(UNIT=13,FILE='SPIN'//VASPSUFF)
  ELSE IF (TAG.EQ.33) THEN
     OPEN(UNIT=13,FILE='SPIN.UP'//VASPSUFF)
  END IF
  INFILE='CHG'
  CALL READRHO
  CALL WRITEPOS
  WRITE(13,*)
  WRITE(13,'(3I5)') NGX,NGY,NGZ
  IF (TAG.EQ.31) THEN
     WRITE(13,'(5E17.8E2)') (((CHGRHO(I,J,K),I=1,NGX),J=1,NGY),K=1,NGZ)
     PROGRESS='Written CHARGE.vasp File!'
  ELSEIF (TAG.EQ.32) THEN
     WRITE(13,'(5E17.8E2)') (((SPINRHO(I,J,K),I=1,NGX),J=1,NGY),K=1,NGZ)
     PROGRESS='Written SPIN.vasp File!'
  ELSEIF (TAG.EQ.33) THEN
     WRITE(13,'(5E17.8E2)') (((((CHGRHO(I,J,K)+SPINRHO(I,J,K))/2.0),I=1, &
                                NGX),J=1,NGY),K=1,NGZ)
     CLOSE(13)
     OPEN(UNIT=13,FILE='SPIN.DOWN'//VASPSUFF)
     CALL WRITEPOS(INFILE)
     WRITE(13,*)
     WRITE(13,'(3I5)') NGX,NGY,NGZ
     WRITE(13,'(5E17.8E2)') (((((CHGRHO(I,J,K)-SPINRHO(I,J,K))/2.0),I=1, &
                                NGX),J=1,NGY),K=1,NGZ)
     PROGRESS='Written SPIN.UP.vasp & SPIN.DOWN.vasp Files!'
  END IF
  CLOSE(12)
  CLOSE(13)
  CALL READPRT
RETURN
END SUBROUTINE 
