SUBROUTINE WRITEPOS
! COPYRIGHT (C) 2009 V. WANG
! THIS FILE IS DISTRIBUTED UNDER THE TERMS OF THE GNU GENERAL PUBLIC LICENSE.
! SEE THE FILE COPYING FOR LICENSE DETAILS.
  USE MODULE
  IMPLICIT NONE
  INTEGER :: I, J, K

  WRITE(13,*) TITLE
  WRITE(13,'(F6.3)') SCALING
  WRITE(13,'(3F14.8)')((REALVECTOR(I,J),J=1,3),I=1,3)
  IF (VASP5 .EQV. .TRUE.) THEN
     WRITE(13,'(10A5)') (ATOMSYMBOL(I),I=1,ATOMTYPE)
  ENDIF
  WRITE(13,'(3I5)')(NATOMS(I),I=1,ATOMTYPE)
  WRITE(13,'(A8)')'DIRECT'
  K=1
  DO I=1,ATOMTYPE
     DO J=1,NATOMS(I)
        WRITE(13,"(3F14.8,A6)")ATOMPOS(K,1),ATOMPOS(K,2),ATOMPOS(K,3),&
                               TRIM(ADJUSTL(ATOMSYMBOL(I)))
        K=K+1
     END DO
  END DO
!  DO I=1,TOTALATOMS
!      WRITE(13,'(3F14.6)')ATOMPOS(I,1),ATOMPOS(I,2),ATOMPOS(I,3)
!  END DO
  RETURN
END SUBROUTINE
